/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.gov.justice.digital.hmpps.interventionscatalogue.deliusconsumer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
