server:
  port : 8081
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'health, info, ping, mappings'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
    info:
      cache:
        time-to-live: 2000ms
graceful:
  shutdown:
    enabled: true
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

sqs:
  endpoint:
    url: http://localhost:4576
  provider: localstack
#  aws:
#    access:
#      key:
#        id:
#    secret:
#      access:
#        key:
cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-2
